language: cpp

matrix:
  include:
    - os: windows
      env: BUILD_CONFIGURATION=Debug
    - os: windows
      env: BUILD_CONFIGURATION=Release
    - os: linux
      dist: trusty
      group: travis_lts
      sudo: required
      env: BUILD_CONFIGURATION=Debug
    - os: linux
      dist: trusty
      group: travis_lts
      sudo: required
      env: BUILD_CONFIGURATION=Release
    - os: osx
      osx_image: xcode9.1
      env: BUILD_CONFIGURATION=Debug
    - os: osx
      osx_image: xcode9.1
      env: BUILD_CONFIGURATION=Release

before_install:
  - . .travis/before-install.sh

install:
  - . .travis/install.sh

script:
  - mkdir build
  - cd build
  - . ../.travis/build.sh

# FIXME: (alkurbatov): Temporary disable documentation generator.
# This should be changed as we don't want/can push to Blizzard repos.
#after_success:
#  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && cd $TRAVIS_BUILD_DIR && ./generate_and_deploy_doxygen.sh'
